import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Image,
  Alert,
  Share,
  Dimensions,
  TextInput,
  ActivityIndicator,
  Animated
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import { useTheme } from '../contexts/ThemeContext';
import { useAuth } from '../contexts/AuthContext';
import { apiService } from '../services/apiService';

const { width } = Dimensions.get('window');

interface AnalysisResult {
  id: string;
  signal: {
    action: 'BUY' | 'SELL' | 'HOLD';
    confidence: number;
    entryPoint: number;
    takeProfit: number[];
    stopLoss: number;
    riskReward: number;
    timeframe: string;
  };
  reasoning: {
    primary: string;
    secondary: string[];
    risks: string[];
    catalysts: string[];
  };
  chartAnalysis: {
    detectedPatterns: Array<{
      type: string;
      confidence: number;
      description?: string;
    }>;
    technicalIndicators: Array<{
      name: string;
      value: number;
      signal: string;
    }>;
    supportLevels: number[];
    resistanceLevels: number[];
    volume: string;
    trend: string;
  };
  marketContext: {
    symbol: string;
    timeframe: string;
    marketType: string;
  };
  webSearchResults: Array<{
    query: string;
    results: Array<{
      title: string;
      snippet: string;
      source: string;
    }>;
  }>;
  timestamp: string;
  processingTime: number;
}

interface RouteParams {
  analysis: AnalysisResult;
  metadata: any;
  imageUri?: string;
  imageUris?: string[];
}

type ResultScreenRouteProp = RouteProp<{ Result: RouteParams }, 'Result'>;

const ResultScreen: React.FC = () => {
  const navigation = useNavigation();
  const route = useRoute<ResultScreenRouteProp>();
  const { theme } = useTheme();
  const { user } = useAuth();
  
  useEffect(() => {
    Animated.parallel([
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 800,
        useNativeDriver: true,
      }),
      Animated.timing(slideAnim, {
        toValue: 0,
        duration: 800,
        useNativeDriver: true,
      }),
      Animated.timing(confidenceAnim, {
        toValue: analysis.signal.confidence / 100,
        duration: 1500,
        useNativeDriver: false,
      })
    ]).start();
  }, []);
  
  const { analysis, metadata, imageUri, imageUris } = route.params;
  const displayImages = imageUris || (imageUri ? [imageUri] : []);
  
  const [feedbackRating, setFeedbackRating] = useState<number | null>(null);
  const [isSubmittingFeedback, setIsSubmittingFeedback] = useState(false);
  const [chatMessages, setChatMessages] = useState<Array<{user: string, ai: string, timestamp: Date}>>([]);
  const [chatInput, setChatInput] = useState('');
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [showChat, setShowChat] = useState(false);
  
  const [fadeAnim] = useState(new Animated.Value(0));
  const [slideAnim] = useState(new Animated.Value(30));
  const [confidenceAnim] = useState(new Animated.Value(0));

  const submitFeedback = async (rating: number) => {
    try {
      setIsSubmittingFeedback(true);
      await apiService.submitFeedback(analysis.id, { rating });
      setFeedbackRating(rating);
      Alert.alert('Thank You', 'Your feedback has been submitted successfully.');
    } catch (error) {
      console.error('Feedback submission failed:', error);
      Alert.alert('Error', 'Failed to submit feedback. Please try again.');
    } finally {
      setIsSubmittingFeedback(false);
    }
  };

  const shareAnalysis = async () => {
    try {
      const message = `Huntr AI Trading Signal:\n\n` +
        `Signal: ${analysis.signal.action}\n` +
        `Confidence: ${analysis.signal.confidence}%\n` +
        `Entry: ${analysis.signal.entryPoint}\n` +
        `Take Profit: ${analysis.signal.takeProfit.join(', ')}\n` +
        `Stop Loss: ${analysis.signal.stopLoss}\n\n` +
        `Analysis: ${analysis.reasoning.primary}\n\n` +
        `Generated by Huntr AI`;

      await Share.share({
        message: message,
      });
    } catch (error) {
      console.error('Share failed:', error);
    }
  };

  const goBack = () => {
    navigation.goBack();
  };

  const goHome = () => {
    navigation.navigate('Home' as never);
  };

  const analyzeAnother = () => {
    navigation.navigate('Analysis' as never);
  };

  const sendChatMessage = async () => {
    if (!chatInput.trim()) return;
    
    const userMessage = chatInput.trim();
    setChatInput('');
    setIsChatLoading(true);
    
    // Add user message immediately
    const newMessage = {
      user: userMessage,
      ai: '',
      timestamp: new Date()
    };
    setChatMessages(prev => [...prev, newMessage]);
    
    try {
      const response = await apiService.chatWithAnalysis(analysis.id, userMessage);
      
      // Update the last message with AI response
      setChatMessages(prev => {
        const updated = [...prev];
        updated[updated.length - 1] = {
          ...updated[updated.length - 1],
          ai: response.data.message
        };
        return updated;
      });
    } catch (error) {
      console.error('Chat error:', error);
      
      // Update with error message
      setChatMessages(prev => {
        const updated = [...prev];
        updated[updated.length - 1] = {
          ...updated[updated.length - 1],
          ai: 'Sorry, I encountered an error. Please try again.'
        };
        return updated;
      });
    } finally {
      setIsChatLoading(false);
    }
  };

  const getSignalColor = (action: string) => {
    switch (action) {
      case 'BUY': return theme.buy;
      case 'SELL': return theme.sell;
      case 'HOLD': return theme.hold;
      default: return theme.textSecondary;
    }
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 80) return theme.buy;
    if (confidence >= 60) return theme.warning;
    return theme.error;
  };

  const formatPrice = (price: number) => {
    if (price === 0) return 'N/A';
    return price.toLocaleString('en-US', { 
      minimumFractionDigits: 2, 
      maximumFractionDigits: 6 
    });
  };

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      paddingTop: 60,
      paddingHorizontal: 24,
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    backButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: theme.surface,
    },
    backButtonText: {
      color: theme.text,
      fontSize: 16,
    },
    shareButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: theme.surface,
    },
    shareButtonText: {
      color: theme.primary,
      fontSize: 16,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.text,
      marginTop: 16,
    },
    scrollContent: {
      paddingHorizontal: 24,
      paddingBottom: 100,
    },
    chartPreview: {
      marginRight: 12,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: theme.surface,
      position: 'relative',
    },
    chartImage: {
      width: 200,
      height: 120,
    },
    signalCard: {
      backgroundColor: theme.card,
      borderRadius: 20,
      padding: 24,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
    },
    signalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    signalBadge: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 25,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    signalText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    confidenceContainer: {
      alignItems: 'flex-end',
    },
    confidenceValue: {
      fontSize: 32,
      fontWeight: 'bold',
      marginBottom: 4,
    },
    confidenceBar: {
      width: 60,
      height: 4,
      backgroundColor: theme.surface,
      borderRadius: 2,
      marginBottom: 4,
      overflow: 'hidden',
    },
    confidenceFill: {
      height: '100%',
      borderRadius: 2,
    },
    confidenceLabel: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    tradingDetails: {
      marginTop: 16,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    detailLabel: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    detailValue: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
    },
    takeProfitValues: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.buy,
    },
    reasoningCard: {
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 20,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 12,
    },
    primaryReason: {
      fontSize: 16,
      color: theme.text,
      lineHeight: 24,
      marginBottom: 16,
    },
    subSection: {
      marginBottom: 16,
    },
    subSectionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 8,
    },
    bulletPoint: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 6,
    },
    bullet: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.primary,
      marginTop: 8,
      marginRight: 8,
    },
    bulletText: {
      fontSize: 14,
      color: theme.text,
      flex: 1,
      lineHeight: 20,
    },
    chartAnalysisCard: {
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 20,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    patternItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    patternName: {
      fontSize: 14,
      color: theme.text,
      flex: 1,
    },
    patternConfidence: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
    },
    indicatorItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 6,
    },
    indicatorName: {
      fontSize: 14,
      color: theme.text,
      flex: 1,
    },
    indicatorValue: {
      fontSize: 14,
      color: theme.textSecondary,
      marginRight: 8,
    },
    indicatorSignal: {
      fontSize: 12,
      fontWeight: '600',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 8,
      backgroundColor: theme.surface,
    },
    levelsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    levelChip: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    levelText: {
      fontSize: 12,
      color: theme.text,
    },
    feedbackCard: {
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 20,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    feedbackTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 12,
    },
    ratingContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 16,
      marginBottom: 16,
    },
    ratingButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    ratingButtonActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    ratingText: {
      fontSize: 18,
      color: theme.text,
    },
    ratingTextActive: {
      color: '#FFFFFF',
    },
    actionButtons: {
      flexDirection: 'row',
      gap: 12,
      paddingHorizontal: 24,
      paddingBottom: 32,
    },
    actionButton: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 16,
      alignItems: 'center',
    },
    secondaryButton: {
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    secondaryButtonText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '600',
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: 'bold',
    },
    metadataCard: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
    },
    metadataRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    metadataLabel: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    metadataValue: {
      fontSize: 12,
      color: theme.text,
      fontWeight: '600',
    },
    chatCard: {
      backgroundColor: theme.card,
      borderRadius: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    chatHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    chatTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
    },
    chatToggle: {
      fontSize: 18,
      color: theme.primary,
    },
    chatContent: {
      maxHeight: 300,
    },
    chatMessages: {
      padding: 16,
      maxHeight: 300,
    },
    messageContainer: {
      marginBottom: 16,
    },
    userMessage: {
      backgroundColor: theme.primary,
      padding: 12,
      borderRadius: 12,
      alignSelf: 'flex-end',
      maxWidth: '80%',
      marginBottom: 4,
    },
    userMessageText: {
      color: '#FFFFFF',
      fontSize: 14,
    },
    aiMessage: {
      backgroundColor: theme.surface,
      padding: 12,
      borderRadius: 12,
      alignSelf: 'flex-start',
      maxWidth: '80%',
      flexDirection: 'row',
      alignItems: 'center',
    },
    aiMessageText: {
      color: theme.text,
      fontSize: 14,
      lineHeight: 20,
      flex: 1,
    },
    chatInputContainer: {
      flexDirection: 'row',
      padding: 16,
      gap: 12,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    chatInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      fontSize: 14,
      color: theme.text,
      backgroundColor: theme.surface,
    },
    sendButton: {
      backgroundColor: theme.primary,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      justifyContent: 'center',
    },
    sendButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '600',
    },
    emptyChat: {
      padding: 16,
      alignItems: 'center',
    },
    emptyChatText: {
      color: theme.textSecondary,
      fontSize: 14,
      textAlign: 'center',
    },
    chartsSection: {
      marginVertical: 20,
    },
    chartsSectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    chartsScroll: {
      marginBottom: 8,
    },
    chartNumber: {
      position: 'absolute',
      top: 8,
      left: 8,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      borderRadius: 12,
      width: 24,
      height: 24,
      justifyContent: 'center',
      alignItems: 'center',
    },
    chartNumberText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: 'bold',
    },
  });

  return (
    <View style={styles.container}>
      <Animated.View style={[
        { flex: 1 },
        {
          opacity: fadeAnim,
          transform: [{ translateY: slideAnim }]
        }
      ]}>
      <View style={styles.header}>
        <View style={styles.headerRow}>
          <TouchableOpacity style={styles.backButton} onPress={goBack}>
            <Text style={styles.backButtonText}>←</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.shareButton} onPress={shareAnalysis}>
            <Text style={styles.shareButtonText}>Share</Text>
          </TouchableOpacity>
        </View>
        <Text style={styles.headerTitle}>Analysis Results</Text>
      </View>

      <ScrollView 
        style={{ flex: 1 }}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {displayImages.length > 0 && (
          <View style={styles.chartsSection}>
            <Text style={styles.chartsSectionTitle}>
              {displayImages.length > 1 ? `${displayImages.length} Charts Analyzed` : 'Chart Analyzed'}
            </Text>
            <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.chartsScroll}>
              {displayImages.map((uri, index) => (
                <View key={index} style={styles.chartPreview}>
                  <Image source={{ uri }} style={styles.chartImage} />
                  <View style={styles.chartNumber}>
                    <Text style={styles.chartNumberText}>{index + 1}</Text>
                  </View>
                </View>
              ))}
            </ScrollView>
          </View>
        )}

        <View style={styles.signalCard}>
          <View style={styles.signalHeader}>
            <View style={[styles.signalBadge, { backgroundColor: getSignalColor(analysis.signal.action) }]}>
              <Text style={styles.signalText}>{analysis.signal.action}</Text>
            </View>
            
            <View style={styles.confidenceContainer}>
              <Text style={[styles.confidenceValue, { color: getConfidenceColor(analysis.signal.confidence) }]}>
                {analysis.signal.confidence}%
              </Text>
              <View style={styles.confidenceBar}>
                <Animated.View 
                  style={[
                    styles.confidenceFill,
                    {
                      width: confidenceAnim.interpolate({
                        inputRange: [0, 1],
                        outputRange: ['0%', '100%']
                      }),
                      backgroundColor: getConfidenceColor(analysis.signal.confidence)
                    }
                  ]}
                />
              </View>
              <Text style={styles.confidenceLabel}>Confidence</Text>
            </View>
          </View>

          <View style={styles.tradingDetails}>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Entry Point</Text>
              <Text style={styles.detailValue}>{formatPrice(analysis.signal.entryPoint)}</Text>
            </View>
            
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Take Profit</Text>
              <Text style={styles.takeProfitValues}>
                {analysis.signal.takeProfit.map(tp => formatPrice(tp)).join(' • ')}
              </Text>
            </View>
            
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Stop Loss</Text>
              <Text style={[styles.detailValue, { color: theme.sell }]}>
                {formatPrice(analysis.signal.stopLoss)}
              </Text>
            </View>
            
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Risk/Reward</Text>
              <Text style={styles.detailValue}>1:{analysis.signal.riskReward}</Text>
            </View>
            
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Timeframe</Text>
              <Text style={styles.detailValue}>{analysis.signal.timeframe}</Text>
            </View>
          </View>
        </View>

        <View style={styles.reasoningCard}>
          <Text style={styles.cardTitle}>Analysis Reasoning</Text>
          
          <Text style={styles.primaryReason}>{analysis.reasoning.primary}</Text>
          
          {analysis.reasoning.catalysts.length > 0 && (
            <View style={styles.subSection}>
              <Text style={styles.subSectionTitle}>Positive Factors</Text>
              {analysis.reasoning.catalysts.map((catalyst, index) => (
                <View key={index} style={styles.bulletPoint}>
                  <View style={styles.bullet} />
                  <Text style={styles.bulletText}>{catalyst}</Text>
                </View>
              ))}
            </View>
          )}
          
          {analysis.reasoning.risks.length > 0 && (
            <View style={styles.subSection}>
              <Text style={styles.subSectionTitle}>Risk Factors</Text>
              {analysis.reasoning.risks.map((risk, index) => (
                <View key={index} style={styles.bulletPoint}>
                  <View style={[styles.bullet, { backgroundColor: theme.error }]} />
                  <Text style={styles.bulletText}>{risk}</Text>
                </View>
              ))}
            </View>
          )}
        </View>

        <View style={styles.chartAnalysisCard}>
          <Text style={styles.cardTitle}>Technical Analysis</Text>
          
          {analysis.chartAnalysis.detectedPatterns.length > 0 && (
            <View style={styles.subSection}>
              <Text style={styles.subSectionTitle}>Detected Patterns</Text>
              {analysis.chartAnalysis.detectedPatterns.map((pattern, index) => (
                <View key={index} style={styles.patternItem}>
                  <Text style={styles.patternName}>{pattern.type}</Text>
                  <Text style={styles.patternConfidence}>{pattern.confidence}%</Text>
                </View>
              ))}
            </View>
          )}
          
          {analysis.chartAnalysis.technicalIndicators.length > 0 && (
            <View style={styles.subSection}>
              <Text style={styles.subSectionTitle}>Technical Indicators</Text>
              {analysis.chartAnalysis.technicalIndicators.map((indicator, index) => (
                <View key={index} style={styles.indicatorItem}>
                  <Text style={styles.indicatorName}>{indicator.name}</Text>
                  <Text style={styles.indicatorValue}>{indicator.value}</Text>
                  <Text style={[
                    styles.indicatorSignal,
                    { color: indicator.signal === 'bullish' ? theme.buy : indicator.signal === 'bearish' ? theme.sell : theme.textSecondary }
                  ]}>
                    {indicator.signal}
                  </Text>
                </View>
              ))}
            </View>
          )}
          
          {(analysis.chartAnalysis.supportLevels.length > 0 || analysis.chartAnalysis.resistanceLevels.length > 0) && (
            <View style={styles.subSection}>
              {analysis.chartAnalysis.supportLevels.length > 0 && (
                <>
                  <Text style={styles.subSectionTitle}>Support Levels</Text>
                  <View style={styles.levelsContainer}>
                    {analysis.chartAnalysis.supportLevels.map((level, index) => (
                      <View key={index} style={styles.levelChip}>
                        <Text style={styles.levelText}>{formatPrice(level)}</Text>
                      </View>
                    ))}
                  </View>
                </>
              )}
              
              {analysis.chartAnalysis.resistanceLevels.length > 0 && (
                <>
                  <Text style={styles.subSectionTitle}>Resistance Levels</Text>
                  <View style={styles.levelsContainer}>
                    {analysis.chartAnalysis.resistanceLevels.map((level, index) => (
                      <View key={index} style={styles.levelChip}>
                        <Text style={styles.levelText}>{formatPrice(level)}</Text>
                      </View>
                    ))}
                  </View>
                </>
              )}
            </View>
          )}
        </View>

        <View style={styles.chatCard}>
        <TouchableOpacity style={styles.chatHeader} onPress={() => setShowChat(!showChat)}>
          <Text style={styles.chatTitle}>Ask about this analysis</Text>
          <Text style={styles.chatToggle}>{showChat ? '−' : '+'}</Text>
        </TouchableOpacity>
        
        {showChat && (
          <View style={styles.chatContent}>
            {chatMessages.length > 0 ? (
              <ScrollView 
                style={styles.chatMessages} 
                showsVerticalScrollIndicator={false}
                ref={ref => {
                  if (ref && chatMessages.length > 0) {
                    ref.scrollToEnd({ animated: true });
                  }
                }}
              >
                {chatMessages.map((msg, index) => (
                  <View key={index} style={styles.messageContainer}>
                    <View style={styles.userMessage}>
                      <Text style={styles.userMessageText}>{msg.user}</Text>
                    </View>
                    {msg.ai ? (
                      <View style={styles.aiMessage}>
                        <Text style={styles.aiMessageText}>{msg.ai}</Text>
                      </View>
                    ) : (
                      <View style={styles.aiMessage}>
                        <ActivityIndicator size="small" color={theme.primary} />
                        <Text style={[styles.aiMessageText, { marginLeft: 8 }]}>Thinking...</Text>
                      </View>
                    )}
                  </View>
                ))}
              </ScrollView>
            ) : (
              <View style={styles.emptyChat}>
                <Text style={styles.emptyChatText}>
                  Ask questions about the analysis, risk management, or market conditions
                </Text>
              </View>
            )}
            
            <View style={styles.chatInputContainer}>
              <TextInput
                style={styles.chatInput}
                placeholder="Ask about this analysis..."
                placeholderTextColor={theme.textSecondary}
                value={chatInput}
                onChangeText={setChatInput}
                multiline
                maxLength={200}
                editable={!isChatLoading}
                returnKeyType="send"
                onSubmitEditing={sendChatMessage}
                blurOnSubmit={false}
              />
              <TouchableOpacity 
                style={[styles.sendButton, (!chatInput.trim() || isChatLoading) && { opacity: 0.5 }]}
                onPress={sendChatMessage}
                disabled={!chatInput.trim() || isChatLoading}
              >
                <Text style={styles.sendButtonText}>Send</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}
        </View>

        <View style={styles.metadataCard}>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Symbol</Text>
            <Text style={styles.metadataValue}>{analysis.marketContext.symbol}</Text>
          </View>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Market Type</Text>
            <Text style={styles.metadataValue}>{analysis.marketContext.marketType}</Text>
          </View>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Processing Time</Text>
            <Text style={styles.metadataValue}>{(analysis.processingTime / 1000).toFixed(1)}s</Text>
          </View>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Web Search</Text>
            <Text style={styles.metadataValue}>
              {analysis.webSearchResults.length > 0 ? 'Enhanced' : 'Basic'}
            </Text>
          </View>
          {displayImages.length > 1 && (
            <View style={styles.metadataRow}>
              <Text style={styles.metadataLabel}>Analysis Type</Text>
              <Text style={styles.metadataValue}>Multi-Timeframe</Text>
            </View>
          )}
          {analysis.chartAnalysis.timeframeAlignment && (
            <View style={styles.metadataRow}>
              <Text style={styles.metadataLabel}>Timeframe Alignment</Text>
              <Text style={[styles.metadataValue, {
                color: analysis.chartAnalysis.timeframeAlignment === 'aligned' ? theme.buy :
                       analysis.chartAnalysis.timeframeAlignment === 'mixed' ? theme.warning : theme.error
              }]}>
                {analysis.chartAnalysis.timeframeAlignment}
              </Text>
            </View>
          )}
        </View>

        {!feedbackRating && !metadata?.fromHistory && (
          <View style={styles.feedbackCard}>
            <Text style={styles.feedbackTitle}>Rate this Analysis</Text>
            <View style={styles.ratingContainer}>
              {[1, 2, 3, 4, 5].map((rating) => (
                <TouchableOpacity
                  key={rating}
                  style={styles.ratingButton}
                  onPress={() => submitFeedback(rating)}
                  disabled={isSubmittingFeedback}
                >
                  <Text style={styles.ratingText}>{rating}</Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>
        )}
      </ScrollView>

      <View style={styles.actionButtons}>
        <TouchableOpacity style={[styles.actionButton, styles.secondaryButton]} onPress={goHome}>
          <Text style={styles.secondaryButtonText}>Home</Text>
        </TouchableOpacity>
        
        <TouchableOpacity style={styles.actionButton} onPress={analyzeAnother}>
          <LinearGradient
            colors={['#00D4FF', '#0099CC']}
            style={[StyleSheet.absoluteFill, { borderRadius: 12 }]}
          />
          <Text style={styles.primaryButtonText}>Analyze Another</Text>
        </TouchableOpacity>
      </View>
      </Animated.View>
    </View>
  );
};

export default ResultScreen;